### PR TITLE
fix: language bar links to invalid URLs

### LINKED ISSUE #715: Change the behavior on a language change
Currently, if you go to this link 
https://constructs.dev/packages/constructs/v/3.3.161/api/constructsconstruct?lang=python

and change the language to Java, you get an error page.

We should make sure than whenever the link includes a reference to a header in the documentation (in this case /api/constructsconstruct and the user presses another programming language it will reload the entire page, means: the link will be https://constructs.dev/packages/constructs/v/3.3.161/?lang=java and not https://constructs.dev/packages/constructs/v/3.3.161/api/constructsconstruct?lang=java

### PR DESCRIPTION
**Pull request by Chriscbr**
Fixes #715

### CODE REVIEW

File: src/components/LanguageBar/LanguageBar.tsx [hunk 1]
```diff
@@ -17,8 +20,9 @@ export interface LanguageBarProps {
 export const LanguageBar: FunctionComponent<LanguageBarProps> = ({
   targetLanguages,
   selectedLanguage,
-  setSelectedLanguage,
 }) => {
+  const { name, version } = usePackageState();
```
Comment (Chriscbr) [inline src/components/LanguageBar/LanguageBar.tsx:24]: I wasn't sure if there's any advantage/disadvantage retrieving state here or passing package state from the parent component (`LanguageSelection`). LMK if either is better

Comment (gabewomble) [reply src/components/LanguageBar/LanguageBar.tsx:24]: I think this is fine 👍

**Review by gabewomble — APPROVED** [review]
