### PR TITLE
fix: multiple of same package appears in search results

### LINKED ISSUE #585: Add major version to the package card and package page
Some packages have several major versions. Their cards then look as clone of each other unless we add the major version. 

In addition, it's a helpful metadata for the package page.

### PR DESCRIPTION
**Pull request by Chriscbr**
Fixes #585

Instead of showing the major version of a package (or major version of the CDK framework) to the package cards, we filter out packages appearing multiple times with different major versions from search results, always preferring to show the highest major version of the package that satisfies the search filters.

For example, if you search for `@aws-cdk/cx-api`, by default only one card is shown, that links to `@aws-cdk/cx-api@2` that supports CDK v2. But if you apply a filter for AWS CDK v1, then `@aws-cdk/cx-api@1` is shown.

### CODE REVIEW

File: src/api/catalog-search/catalog-search.ts [hunk 1]
```diff
@@ -223,6 +225,25 @@ export class CatalogSearchAPI {
...
+   * one with the latest version.
+   */
+  private dedup(results: CatalogSearchResults): CatalogSearchResults {
+    const dedupedResults: Map<string, ExtendedCatalogPackage> = new Map();
+
+    results.forEach((pkg) => {
+      const maybePkg = dedupedResults.get(pkg.name);
+
+      // include the result if the package is new, or it has a higher major version
+      if (!maybePkg || (maybePkg && maybePkg.major < pkg.major)) {
```
Comment (eladb) [inline src/api/catalog-search/catalog-search.ts:239]: This assumes that the latest version is the "most major" version but that's not necessarily true. We can't assume that.

Here's a concrete example that @addihorowitz and I ran into:

The latest version of [cdk-dynamo-table-viewer](https://www.npmjs.com/package/cdk-dynamo-table-viewer) is v0.1.142, while the largest major version is v3.1.2. You'll also notice that 3.1.2 does not have a description (which was added later).

The download numbers you get from npm are only for the last version published under the `latest` dist tag, so if we are deduplicating, we should only show this version and not just the latest major.

**Review by eladb — CHANGES_REQUESTED** [review]
See comment about latest versus last-major.

File: src/api/catalog-search/catalog-search.ts (hunk 1 above)
Comment (Chriscbr) [reply src/api/catalog-search/catalog-search.ts:239]: I see, yeah this is a great callout. Looks like what we should probably do is track the NPM dist tags in our backend, or at the minimum try to label in the catalog which major version is tied to "latest" so that package can take priority during this de-duplication.

This is probably a bit of logic that we could tack on during catalog building or ingestion, though the truth is that it's technically possible for library authors to change which version is tagged with "latest" at any time. So the most reliable way to ensure this data doesn't get out of sync would be to update it whenever we ingest a new package AND on some periodic schedule. (which I think implies storing the data someplace besides the catalog). But this edge case is probably small enough that we could defer implementing this "periodic refresh" logic until a later date. 

It would be nice if we could "cheat" by showing the most recently published version as a proxy for the "latest"-tagged version, but that will produce bad results for packages where multiple tags (like "latest" and "next") are both being actively published to.

For now I'll mark this PR as a draft because of the concerns you mentioned.

Comment (eladb) [reply src/api/catalog-search/catalog-search.ts:239]: Curious, when you get download numbers from npm, do you have a version indication of the module or is it just name?

Comment (Chriscbr) [reply src/api/catalog-search/catalog-search.ts:239]: It's just by package name. There's no publicly available API for getting download numbers per version.

Comment (Chriscbr) [reply src/api/catalog-search/catalog-search.ts:239]: > The download numbers you get from npm are only for the last version published under the latest dist tag, so if we are deduplicating, we should only show this version and not just the latest major.

Sorry, I missed this part of your first comment. To clarify ,the npm download numbers we're using are for all versions, not for the "latest" version. For example, https://www.npmjs.com/package/@aws-cdk/cx-api has > 1M downloads (which is also reflected on Construct Hub) but only when summed over all versions.

Following on my earlier comment, I'm starting to think having logic dependent on the "latest" tag could be tricky because it's possible the "latest" tag could point to a package version that hasn't been ingested OR a version that can't be ingested OR a version that has been deny listed. And there's no way to identify what was previously tagged as "latest" in the past. It's possible this is still the correct thing to do, but there's more edge cases than expected...

Comment (gabewomble) [reply src/api/catalog-search/catalog-search.ts:239]: I believe our best bet would be to just show the most recently updated version until we can support the _latest_ tag. This will at least be pretty consistent with how npm behaves. IMO the above scenario feels like a bit of an edge case, and at the end of the day, we need to show a single result that links to a page that has a version dropdown rather than potentially confusing users with multiple near-identical results. @eladb @Chriscbr Let me know what you think of this.

Comment (Chriscbr) [reply src/api/catalog-search/catalog-search.ts]: I'm OK with this. This will be a little bit weird for packages that publish to multiple tags, but I think it's still a net better experience. Updated the PR.

File: src/api/package/packages.ts [hunk 2]
```diff
@@ -11,6 +11,7 @@ export interface Author {
 export interface CatalogPackage {
   name: string;
   languages?: Partial<Record<Language, Record<string, unknown>>>;
+  major: number;
```
Comment (eladb) [inline src/api/package/packages.ts:14]: Is this needed?

File: src/api/catalog-search/catalog-search.ts [hunk 3]
```diff
@@ -191,6 +191,8 @@ export class CatalogSearchAPI {
       results = this.sort(results, sort);
     }
 
+    results = this.dedup(results);
```
Comment (eladb) [inline src/api/catalog-search/catalog-search.ts:194]: No test?

File: src/api/catalog-search/catalog-search.ts [hunk 4]
```diff
@@ -283,6 +285,27 @@ export class CatalogSearchAPI {
...
   }
 
+  /**
+   * De-duplicates packages that appear multiple times, keeping the
+   * most recently published one.
+   */
+  private dedup(results: CatalogSearchResults): CatalogSearchResults {
+    const dedupedResults: Map<string, ExtendedCatalogPackage> = new Map();
+
+    results.forEach((pkg) => {
```
Comment (eladb) [inline src/api/catalog-search/catalog-search.ts:295]: Style nit: prefer `for-if` instead of `forEach()`. It's easier to read and maintain in the long term. For example, it is not possible to `break` a `forEach()` loop.

File: src/api/package/packages.ts (hunk 2 above)
Comment (eladb) [inline src/api/package/packages.ts:14]: Is this needed?

**Review by eladb — CHANGES_REQUESTED** [review]

File: src/api/package/packages.ts (hunk 2 above)
Comment (gabewomble) [reply src/api/package/packages.ts:14]: This is actually a fix on the type - `CatalogPackage` represents data we get from the backend, so this annotation was previously missing

**Comment by Chriscbr** [comment]
Several tests needed tweaking since they tend to assume that no de-duplication goes on. Initially I thought that was OK, but now I'm realizing that for #679 I will actually need to have a way to retrieve un-de-duplicated results, so I'm going to switch "dedup" into being an optional search flag.

**Comment by gabewomble** [comment]
@Chriscbr I think it makes sense to `dedup` on search by default with a flag to disable it, but IMO it would be nice to have a method on the search such as `findByName` which could just return a list or map of packages that exact match the name

**Comment by Chriscbr** [comment]
@gabewomble Good suggestion, I think I'll add a method like that in my other PR.

**Comment by Chriscbr** [comment]
@eladb @gabewomble Is there anything blocking this UX fix?

**Comment by gabewomble** [comment]
Nothing on my end 👍

File: src/api/catalog-search/catalog-search.ts [hunk 5]
```diff
@@ -92,6 +92,7 @@ export interface CatalogSearchParams {
   query?: string;
   filters?: CatalogSearchFilters;
   sort?: CatalogSearchSort;
+  dedup?: boolean;
```
Comment (gabewomble) [inline src/api/catalog-search/catalog-search.ts:95]: I think I'd prefer this not to be optional so that behavior is consistent across the board. As is, we'll still get duplicated results from search suggestions. LMK what you think, we could also default this to true as an alternative

**Review by gabewomble — APPROVED** [review]
