### PR TITLE
chore: safari css fixes

### LINKED ISSUE #213: Mobile -  part of the page is blank
(On iPhone) the page is blank after npm install instruction

Reproduce: https://constructs.dev/packages/cdk-iam-generator/v/1.0.4?lang=typescript

### LINKED ISSUE #217: Safari: overflow:hidden applying to a further construct
On Safari https://constructs.dev/packages/cdk-iam-generator/v/1.0.4?lang=typescript - appears to suffer from overflow:hidden applying to a further construct

### PR DESCRIPTION
**Pull request by gabewomble**
Fixes #217
Fixes #213 
Fixes https://github.com/cdklabs/construct-hub-internal/issues/41

Fixes some css oddities in Safari.

### CODE REVIEW

File: src/components/CodePopover/CodePopover.tsx [hunk 1]
```diff
@@ -49,12 +51,14 @@ export const CodePopover: FunctionComponent<CodePopoverProps> = ({
...
   const focusRef = useRef<HTMLButtonElement>(null);
+  const mdBreakpoint = useToken("breakpoints", "md");
+  const [isMd] = useMediaQuery(`(min-width: ${mdBreakpoint})`);
 
   return (
     <Popover
       initialFocusRef={focusRef}
       isLazy
-      placement="bottom-end"
+      placement={isMd ? "bottom-end" : "bottom"}
```
Comment (gabewomble) [inline src/components/CodePopover/CodePopover.tsx:61]: This change is not a bug fix, just centers the code popover with it's trigger on mobile

**Review by RomainMuller — APPROVED** [review]
