### PR TITLE
chore: update home page categories, fixes tag click bug

### LINKED ISSUE #718: Update the categories on the home page
Please change "Kubernetes" to "Containers" (should redirect to /search?q=&keywords=containers&offset=0)
Please add the following categories:
* Compliance (should redirect to /search?q=&keywords=compliance&offset=0) 
* Network (should redirect to /search?q=&keywords=network&offset=0)
* Artificial Intelligence (AI) (should redirect to /search?q=&keywords=artificial+intelligence+(ai)&offset=0)
* Cloud Services Integrations (should redirect to /search?q=&keywords=cloud+services+integrations&offset=0)

Update all the categories so that they will redirect to: /search?q=&keywords=<cateogry_name>&offset=0  as in the examples above. And test it. If for some reason it doesn't work - remove this category. 

@gabewomble can we make sure that the number of categories we display will be adapted by the size of the screen?

### PR DESCRIPTION
**Pull request by gabewomble**
Fixes #718 

Updates the home page categories. Also fixes a bug where clicking on tags on cards would apply a filter with no way to remove the filter.

### CODE REVIEW

**Review by Chriscbr — APPROVED** [review]

File: src/views/Home/Categories.tsx [hunk 1]
```diff
@@ -11,14 +11,24 @@ import testIds from "./testIds";
...
 const DEFAULT_CATEGORIES: Category[] = [
-  { title: "Monitoring", url: getSearchPath({ query: "monitoring" }) },
-  { title: "Kubernetes", url: getSearchPath({ query: "kubernetes" }) },
-  { title: "Serverless", url: getSearchPath({ query: "serverless" }) },
-  { title: "Databases", url: getSearchPath({ query: "databases" }) },
-  { title: "Utilities", url: getSearchPath({ query: "utilities" }) },
-  { title: "Deployment", url: getSearchPath({ query: "deployment" }) },
-  { title: "Websites", url: getSearchPath({ query: "web" }) },
-  { title: "Security", url: getSearchPath({ query: "security" }) },
+  { title: "Monitoring", url: getSearchPath({ keywords: ["monitoring"] }) },
```
Comment (eladb) [inline src/views/Home/Categories.tsx:14]: This can technically be updated from the backend as well

File: src/views/Home/Categories.tsx [hunk 2]
```diff
@@ -11,14 +11,24 @@ import testIds from "./testIds";
  * Categories used if config does not have specific categories
  */
 const DEFAULT_CATEGORIES: Category[] = [
-  { title: "Monitoring", url: getSearchPath({ query: "monitoring" }) },
-  { title: "Kubernetes", url: getSearchPath({ query: "kubernetes" }) },
-  { title: "Serverless", url: getSearchPath({ query: "serverless" }) },
-  { title: "Databases", url: getSearchPath({ query: "databases" }) },
-  { title: "Utilities", url: getSearchPath({ query: "utilities" }) },
-  { title: "Deployment", url: getSearchPath({ query: "deployment" }) },
-  { title: "Websites", url: getSearchPath({ query: "web" }) },
```
Comment (addihorowitz) [inline src/views/Home/Categories.tsx:20]: the query here should be "websites"
